---
- name: Test playbook
  hosts: localhost
  gather_facts: yes
  vars_files:
  - vars/main.yaml
  tasks:
  - name: Create a temp directory to store generated keys and certs
    ansible.builtin.tempfile:
      state: directory
      suffix: fdokeys
    register: tempdir_result

  - name: Set in fact
    ansible.builtin.set_fact:
      fdoKeysdir: "{{ tempdir_result.path }}"

  - name: Generate manufacturer private key and certificate
    ansible.builtin.shell: |
      openssl ecparam -genkey -name prime256v1 -out "{{ fdoKeysdir }}/manufacturer_key.pem" -outform PEM
      openssl req -new -x509 -key "{{ fdoKeysdir }}/manufacturer_key.pem" -inform PEM -out "{{ fdoKeysdir }}/manufacturer_cert.pem" -days 365 \
        -subj "/CN=FDO Manufacturer/O=Test Organization/C=US"  
  - name: Generate Owner private key and cert
    ansible.builtin.shell: |
      openssl ecparam -genkey -name prime256v1 -out "{{ fdoKeysdir }}/owner_key.pem" -outform PEM
      openssl req -new -x509 -key "{{ fdoKeysdir }}/owner_key.pem" -keyform PEM -out "{{ fdoKeysdir }}/owner_cert.pem" -days 365 \
        -subj "/CN=FDO Owner/O=Test Organization/C=US"

  - name: Generate device CA private key and certificate
    ansible.builtin.shell: |
      openssl ecparam -genkey -name prime256v1 -out "{{ fdoKeysdir }}/device_ca_key.pem" -outform PEM
      openssl req -new -x509 -key "{{ fdoKeysdir }}/device_ca_key.pem" -inform PEM -out "{{ fdoKeysdir }}/device_ca_cert.pem" -days 365 \
        -subj "/CN=FDO Device CA/O=Test Organization/C=US"

  - name: load secrets 
    ansible.builtin.include_vars:
      file: "./vars/secrets.yml"
  
  - name: Generate user data config
    ansible.builtin.template:
      src: './templates/user-data.yaml.j2'
      dest: user-data.yaml